### ISSUE TITLE
Feature Suggestion - Sane Defaults for Jest Testing

### ISSUE THREAD

**Issue by bradleyess** [postlight/serverless-babel-starter#18]
Bootstrapping the project from scratch doesn't define any configuration for Jest out of the box. I'm pretty sure we could come up with some sane defaults for basic JS testing and let people expand from there. Perhaps even providing various examples in the readme/wiki.

**Comment by WajeehZantout** [comment]
The latest version of the starter kit has some basic [config](https://github.com/postlight/serverless-babel-starter/blob/master/jest.config.js) for Jest. For more info, check [this](https://github.com/postlight/serverless-babel-starter#test-your-functions-with-jest) section in the readme.
