### ISSUE TITLE
yarn install results in error eslint@5.3.0: The engine "node" is incompatible

### ISSUE THREAD

**Issue by kjetilge** [postlight/serverless-babel-starter#25]
After doing:
```
serverless install --url https://github.com/postlight/serverless-babel-starter --name dynathumbs
```

I get:
```
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error eslint@5.3.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I running node v9.5.0. I've also tried v8.1.0

**Comment by adampash** [comment]
Can you try using `8.10.0`? It's the version in the `.nvmrc` and the version that Lambda uses.

Also, if you check your error message, it says:

`Expected version "^6.14.0 || ^8.10.0 || >=9.10.0".`

So... give that a try and let me know if you're still having problems!

**Comment by adampash** [comment]
I'm going to close this for now. Feel free to come back if you're still having this problem.

Thanks!
Adam
